CREATE TABLE user (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    login_id VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    role ENUM('ADMIN', 'USER') NOT NULL
);

ALTER TABLE user
ADD COLUMN failed_attempts INT DEFAULT 0,
ADD COLUMN locked BOOLEAN DEFAULT false;

ALTER TABLE user AUTO_INCREMENT = 1000;